"""
DroneForge AI - Engineering Report Generator
Generates comprehensive design justification documents with mathematical proofs.
"""

import json
import logging
import math
from typing import Dict, Any, List
from dataclasses import asdict
from datetime import datetime

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates engineering justification reports with mathematical proofs"""
    
    def __init__(self):
        self.report_sections = []
    
    def _to_dict(self, obj):
        """Convert dataclass to dict safely and recursively sanitize enums (BUG-069)"""
        if obj is None:
            return {}
            
        def sanitize(v):
            if hasattr(v, 'value'):
                return v.value
            if isinstance(v, dict):
                return {k2: sanitize(v2) for k2, v2 in v.items()}
            if isinstance(v, list):
                return [sanitize(v2) for v2 in v]
            if hasattr(v, '__dataclass_fields__'):
                return sanitize(asdict(v))
            return v

        if hasattr(obj, '__dataclass_fields__'):
            return sanitize(asdict(obj))
        if isinstance(obj, dict):
            return sanitize(obj)
        if hasattr(obj, '__dict__'):
            return sanitize(obj.__dict__)
        return {}
    
    def generate_full_report(self, state: Dict[str, Any]) -> str:
        """Generate complete engineering justification report"""
        
        report = []
        report.append(self._generate_header(state))
        report.append(self._generate_executive_summary(state))
        report.append(self._generate_mission_analysis(state))
        report.append(self._generate_propulsion_justification(state))
        report.append(self._generate_aerodynamics_analysis(state))
        report.append(self._generate_structural_analysis(state))
        report.append(self._generate_power_analysis(state))
        report.append(self._generate_electronics_justification(state))
        report.append(self._generate_cog_analysis(state))
        report.append(self._generate_software_justification(state))
        report.append(self._generate_wiring_analysis(state))
        report.append(self._generate_regulatory_compliance(state))
        report.append(self._generate_cost_analysis(state))
        report.append(self._generate_appendix(state))
        
        return "\n\n".join(report)
    
    def _generate_header(self, state: Dict) -> str:
        """Generate report header"""
        mission = state.get('mission_statement', 'Drone Design')
        date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        return f"""# DroneForge AI - Engineering Design Justification Report

**Project:** {mission}  
**Generated:** {date}  
**Version:** 1.0  
**Classification:** Engineering Document

---

## Document Control

| Item | Value |
|------|-------|
| Document Type | Engineering Justification Report |
| Design Tool | DroneForge AI Multi-Agent System |
| LLM Provider | {state.get('llm_provider', 'Unknown')} |
| CAD Detail Level | {state.get('cad_detail_level', 'basic')} |

---
"""
    
    def _generate_executive_summary(self, state: Dict) -> str:
        """Generate executive summary"""
        mission_req = self._to_dict(state.get('mission_requirements', {}))
        propulsion = self._to_dict(state.get('propulsion_design', {}))
        power = self._to_dict(state.get('power_design', {}))
        cog = self._to_dict(state.get('cog_analysis', {}))
        validation = self._to_dict(state.get('validation_result', {}))
        
        # Format drone configuration/type enums (BUG-069)
        config = mission_req.get('configuration', 'N/A')
        if hasattr(config, 'value'):
            config_str = config.value
        else:
            config_str = str(config)
            
        drone_type = mission_req.get('drone_type', 'multirotor')
        if hasattr(drone_type, 'value'):
            drone_type_str = drone_type.value
        else:
            drone_type_str = str(drone_type)

        auw = cog.get('total_mass_kg', 0) or propulsion.get('calculations', {}).get('estimated_auw_kg', 2.0)
        
        return f"""## 1. Executive Summary

### 1.1 Design Overview

This report provides engineering justification for the drone design generated by DroneForge AI. 
All component selections are based on physics calculations, not arbitrary choices.

### 1.2 Key Design Parameters

| Parameter | Value | Unit |
|-----------|-------|------|
| Configuration | {config_str} | - |
| Motor Count | {propulsion.get('motor_count', 'N/A')} | units |
| All-Up Weight (AUW) | {auw:.2f} | kg |
| Total Thrust | {propulsion.get('total_thrust_n', 0):.2f} | N |
| Thrust-to-Weight Ratio | {propulsion.get('thrust_to_weight', 0):.2f} | - |
| Flight Time (Calculated) | {power.get('calculated_flight_time_min', 0):.1f} | minutes |
| Maximum Speed | {mission_req.get('max_speed_ms', 0)} | m/s |

### 1.3 Design Validation Status

| Check | Status |
|-------|--------|
| Physics Validation | {'✅ PASSED' if validation.get('physics_valid', False) else '⚠️ REVIEW'} |
| Compatibility Check | {'✅ PASSED' if validation.get('compatibility_valid', False) else '⚠️ REVIEW'} |
| Safety Validation | {'✅ PASSED' if validation.get('safety_valid', False) else '⚠️ REVIEW'} |
| Overall | {'✅ PASSED' if validation.get('all_valid', False) else '⚠️ REQUIRES REVIEW'} |
"""
    
    def _generate_mission_analysis(self, state: Dict) -> str:
        """Generate mission requirements analysis"""
        req = self._to_dict(state.get('mission_requirements', {}))
        
        return f"""## 2. Mission Requirements Analysis

### 2.1 Primary Mission Parameters

| Requirement | Specified Value | Design Consideration |
|-------------|-----------------|---------------------|
| Drone Type | {req.get('drone_type', 'multirotor')} | Determines motor layout and control scheme |
| Configuration | {req.get('configuration', 'quadcopter_x')} | Affects redundancy and lift distribution |
| Payload Mass | {req.get('payload_mass_kg', 0)} kg | Drives motor sizing and battery capacity |
| Payload Type | {req.get('payload_type', 'camera')} | Influences vibration dampening requirements |
| Endurance Required | {req.get('endurance_min', 30)} minutes | Primary driver for battery sizing |
| Operating Altitude | {req.get('max_altitude_m', 120)} m | Affects air density calculations |
| Budget | {req.get('max_cost', 0)} {req.get('currency', 'INR')} | Component selection constraint |

### 2.2 Autonomy Requirements

| Feature | Required | Design Impact |
|---------|----------|---------------|
| Waypoint Navigation | {'Yes' if req.get('waypoint_navigation', False) else 'No'} | GPS + FC with mission planning |
| Obstacle Avoidance | {'Yes' if req.get('obstacle_avoidance', False) else 'No'} | Additional sensors + processing |
| Return to Home | {'Yes' if req.get('return_to_home', False) else 'No'} | GPS + barometer required |
| Geofencing | {'Yes' if req.get('geofencing', False) else 'No'} | FC with geofence support |
| Beyond VLOS | {'Yes' if req.get('beyond_vlos', False) else 'No'} | Extended telemetry range |

### 2.3 Environmental Constraints

- **Temperature Range:** {req.get('temp_min_c', -10)}°C to {req.get('temp_max_c', 40)}°C
- **Wind Resistance:** {req.get('wind_resistance_ms', 8)} m/s
- **Precipitation Resistant:** {'Yes' if req.get('precipitation_resistant', False) else 'No'}
"""
    
    def _generate_propulsion_justification(self, state: Dict) -> str:
        """Generate propulsion system justification with math"""
        propulsion = self._to_dict(state.get('propulsion_design', {}))
        mission_req = self._to_dict(state.get('mission_requirements', {}))
        
        motor_count = propulsion.get('motor_count', 4)
        total_thrust_n = propulsion.get('total_thrust_n', 0)
        hover_throttle = propulsion.get('hover_throttle_percent', 50)
        twratio = propulsion.get('thrust_to_weight', 2.0)
        
        # Get values (BUG-059: read cell count from power calculations)
        power = self._to_dict(state.get('power_design', {}))
        cell_count = power.get('calculations', {}).get('cell_count', propulsion.get('calculations', {}).get('cell_count', 6))
        
        # Get motor specs (BUG-057: use brand fallback)
        motors = propulsion.get('motors', [{}])
        motor = motors[0] if motors else {}
        motor_kv = motor.get('specs', {}).get('kv', motor.get('kv', 2300))
        motor_max_thrust = motor.get('specs', {}).get('max_thrust_g', motor.get('max_thrust_g', 500))
        motor_weight = motor.get('specs', {}).get('weight_g', motor.get('weight_g', 30))
        motor_max_current = motor.get('specs', {}).get('max_current_a', motor.get('max_current_a', 30))
        
        # Format brand/manufacturer safely
        motor_brand = motor.get('brand', motor.get('manufacturer', 'Generic'))
        motor_price = motor.get('price_inr', motor.get('price_usd', 0) * 95)
        
        # Get propeller specs
        props = propulsion.get('propellers', [{}])
        prop = props[0] if props else {}
        prop_diameter = prop.get('diameter_in', prop.get('size_inch', 5))
        prop_pitch = prop.get('pitch_in', prop.get('pitch_inch', 4))
        prop_blades = prop.get('blades', 3)
        
        # Calculate values
        estimated_auw = propulsion.get('calculations', {}).get('estimated_auw_kg', 2.0)
        weight_n = estimated_auw * 9.81
        
        # Required thrust per motor
        required_thrust_per_motor = (weight_n / motor_count) * twratio
        required_thrust_per_motor_g = required_thrust_per_motor / 9.81 * 1000
        
        # Dynamic comparison and status (BUG-044 / BUG-045)
        thrust_status = "✅" if motor_max_thrust >= required_thrust_per_motor_g else "⚠️"
        thrust_symbol = ">=" if motor_max_thrust >= required_thrust_per_motor_g else "<"
        
        # Configuration formatting
        config_str = mission_req.get('configuration', 'quadcopter_x')
        if hasattr(config_str, 'value'):
            config_str = config_str.value
        
        return f"""## 3. Propulsion System Design Justification

### 3.1 Motor Count Selection: {motor_count} Motors

**Justification:** A {config_str} configuration was selected because:

1. **Redundancy:** With {motor_count} motors, the drone can potentially survive a single motor failure
2. **Thrust Distribution:** Load is spread across more motors, reducing individual motor stress
3. **Efficiency:** Each motor operates at a lower percentage of maximum thrust

### 3.2 Motor Selection Mathematical Analysis

#### 3.2.1 Thrust Requirements Calculation

**Given:**
- Estimated All-Up Weight (AUW) = {estimated_auw:.2f} kg
- Required Thrust-to-Weight Ratio = {twratio:.1f}
- Motor Count = {motor_count}

**Calculation:**

$$\\text{{Total Weight Force}} = AUW \\times g = {estimated_auw:.2f} \\times 9.81 = {weight_n:.2f} \\text{{ N}}$$

$$\\text{{Required Total Thrust}} = T/W \\times \\text{{Weight}} = {twratio:.1f} \\times {weight_n:.2f} = {weight_n * twratio:.2f} \\text{{ N}}$$

$$\\text{{Thrust per Motor}} = \\frac{{\\text{{Total Thrust}}}}{{\\text{{Motor Count}}}} = \\frac{{{weight_n * twratio:.2f}}}{{{motor_count}}} = {weight_n * twratio / motor_count:.2f} \\text{{ N}} = {required_thrust_per_motor_g:.0f} \\text{{ g}}$$

#### 3.2.2 Selected Motor Specifications

| Parameter | Value | Justification |
|-----------|-------|---------------|
| Model | {motor_brand} {motor.get('model', 'N/A')} | Matches thrust requirements |
| KV Rating | {motor_kv} KV | Optimized for {cell_count}S battery |
| Max Thrust | {motor_max_thrust} g | {thrust_symbol} {required_thrust_per_motor_g:.0f} g required {thrust_status} |
| Weight | {motor_weight} g | Lightweight for efficiency |
| Max Current | {motor_max_current} A | Within ESC rating |
| Price | ₹{motor_price:.0f} | Within budget constraints |

#### 3.2.3 Motor Selection Criteria vs Alternatives

**Why this motor over alternatives:**

1. **Thrust Margin:** {motor_max_thrust} g {thrust_symbol} {required_thrust_per_motor_g:.0f} g (required) → {(motor_max_thrust / max(required_thrust_per_motor_g, 1.0) * 100 - 100):.0f}% margin
2. **Efficiency:** {motor.get('specs', {}).get('efficiency_g_per_w', 5)} g/W at hover
3. **Availability:** {motor.get('availability', 'in_stock')}
4. **Price-Performance:** Best thrust/₹ ratio in this category

### 3.3 Propeller Selection

#### 3.3.1 Selected Propeller

| Parameter | Value |
|-----------|-------|
| Diameter | {prop_diameter}" |
| Pitch | {prop_pitch}" |
| Blades | {prop_blades} |
| Material | {prop.get('material', 'PC')} |

#### 3.3.2 Propeller Physics

**Propeller Tip Speed:**

$$V_{{tip}} = \\pi \\times D \\times RPM / 60$$

For {prop_diameter}" prop at typical hover RPM of 8000:

$$V_{{tip}} = \\pi \\times {prop_diameter * 0.0254:.4f} \\times 8000 / 60 = {math.pi * prop_diameter * 0.0254 * 8000 / 60:.1f} \\text{{ m/s}}$$

**Static Thrust (Simplified):**

Using the static thrust approximation:

$$T = C_T \\times \\rho \\times n^2 \\times D^4$$

Where:
- $C_T$ ≈ 0.1 (typical for multirotor props)
- $\\rho$ = 1.225 kg/m³ (air density at sea level)
- $n$ = revolutions per second
- $D$ = propeller diameter in meters

### 3.4 Hover Efficiency Analysis

**Hover Current per Motor:**

$$I_{{hover}} = \\frac{{I_{{max}} \\times \\text{{Hover Throttle \\%}}}}{{100}} = \\frac{{{motor_max_current} \\times {hover_throttle}}}{{100}} = {motor_max_current * hover_throttle / 100:.1f} \\text{{ A}}$$

**Total System Hover Current:**

$$I_{{total\\_hover}} = I_{{hover}} \\times \\text{{Motor Count}} = {motor_max_current * hover_throttle / 100:.1f} \\times {motor_count} = {motor_max_current * hover_throttle / 100 * motor_count:.1f} \\text{{ A}}$$

### 3.5 Propulsion System Summary

| Metric | Calculated Value | Status |
|--------|------------------|--------|
| Total System Thrust | {total_thrust_n:.2f} N ({total_thrust_n / 9.81 * 1000:.0f} g) | ✅ |
| Thrust-to-Weight Ratio | {twratio:.2f} | {'✅ ≥ 2.0' if twratio >= 2.0 else '⚠️ < 2.0'} |
| Hover Throttle | {hover_throttle}% | {'✅ < 60%' if hover_throttle < 60 else '⚠️ ≥ 60%'} |
"""
    
    def _generate_aerodynamics_analysis(self, state: Dict) -> str:
        """Generate aerodynamics analysis with math"""
        aero = self._to_dict(state.get('aerodynamics_analysis', {}))
        mission_req = self._to_dict(state.get('mission_requirements', {}))
        
        drag_coef = aero.get('drag_coefficient', 0.8)
        frontal_area = aero.get('frontal_area_m2', 0.03)
        cruise_speed = mission_req.get('cruise_speed_ms', 5)
        air_density = aero.get('calculations', {}).get('air_density_kg_m3', 1.225)
        drag_force = aero.get('drag_force_at_cruise_n', 0.5)
        max_wind = aero.get('max_wind_speed_ms', 10)
        
        # Calculate drag using standard equation
        calculated_drag = 0.5 * air_density * drag_coef * frontal_area * cruise_speed**2
        
        return f"""## 4. Aerodynamics Analysis

### 4.1 Drag Coefficient Estimation

For a multirotor configuration, the drag coefficient is estimated based on:

1. **Frame geometry** (arms, center body)
2. **Motor pods and propellers**
3. **Payload and accessories**

**Estimated Drag Coefficient:** $C_D$ = {drag_coef:.3f}

This value is typical for multirotor UAVs and accounts for:
- Bluff body drag of motor pods
- Interference drag between arms
- Pressure drag from payload

### 4.2 Frontal Area Calculation

**Estimated Frontal Area:** $A$ = {frontal_area:.4f} m²

Components contributing to frontal area:
- Center body: ~40%
- Motor pods: ~30%
- Arms: ~20%
- Payload/camera: ~10%

### 4.3 Drag Force Calculation

Using the standard drag equation:

$$F_D = \\frac{{1}}{{2}} \\rho v^2 C_D A$$

Where:
- $\\rho$ = {air_density:.4f} kg/m³ (air density at operating altitude)
- $v$ = {cruise_speed} m/s (cruise speed)
- $C_D$ = {drag_coef:.3f}
- $A$ = {frontal_area:.4f} m²

**Calculation:**

$$F_D = \\frac{{1}}{{2}} \\times {air_density:.4f} \\times {cruise_speed}^2 \\times {drag_coef:.3f} \\times {frontal_area:.4f}$$

$$F_D = {calculated_drag:.3f} \\text{{ N}}$$

### 4.4 Power Required for Forward Flight

**Power to overcome drag:**

$$P_{{drag}} = F_D \\times v = {calculated_drag:.3f} \\times {cruise_speed} = {calculated_drag * cruise_speed:.2f} \\text{{ W}}$$

This is in addition to hover power requirements.

### 4.5 Wind Resistance Analysis

**Maximum Wind Penetration Speed:** {max_wind:.1f} m/s

This is calculated based on available thrust margin beyond hover requirements.

$$v_{{wind\\_max}} = \\sqrt{{\\frac{{2 \\times (T_{{available}} - W)}}{{\\rho \\times C_D \\times A}}}}$$

### 4.6 Reynolds Number Analysis

For propeller blades at hover:

$$Re = \\frac{{\\rho \\times v \\times L}}{{\\mu}}$$

Where:
- $v$ = tip speed
- $L$ = chord length
- $\\mu$ = dynamic viscosity of air

**Calculated Reynolds Number:** {aero.get('calculations', {}).get('reynolds_number', 30000)}

This indicates the flow regime around the propeller blades.
"""
    
    def _generate_structural_analysis(self, state: Dict) -> str:
        """Generate structural analysis with math"""
        struct = self._to_dict(state.get('structural_design', {}))
        calcs = struct.get('calculations', {})
        
        arm_length = struct.get('arm_length_mm', 200)
        arm_diameter = struct.get('arm_diameter_mm', 16)
        arm_wall = struct.get('arm_wall_thickness_mm', 1.5)
        wheelbase = struct.get('wheelbase_mm', 500)
        max_stress = struct.get('max_bending_stress_mpa', 50)
        safety_factor = struct.get('safety_factor', 5)
        natural_freq = struct.get('natural_frequency_hz', 50)
        material = struct.get('frame_material', 'carbon_fiber')
        
        # Material properties
        materials = {
            'carbon_fiber': {'yield_mpa': 600, 'E_gpa': 70, 'density': 1600},
            'aluminum': {'yield_mpa': 270, 'E_gpa': 69, 'density': 2700},
            'abs': {'yield_mpa': 40, 'E_gpa': 2.3, 'density': 1050}
        }
        mat_props = materials.get(material, materials['carbon_fiber'])
        
        # Calculate moment of inertia for hollow tube
        r_outer = arm_diameter / 2
        r_inner = r_outer - arm_wall
        I = (math.pi / 4) * (r_outer**4 - r_inner**4)
        
        return f"""## 5. Structural Design Analysis

### 5.1 Material Selection: {material.replace('_', ' ').title()}

**Material Properties:**

| Property | Value | Unit |
|----------|-------|------|
| Yield Strength | {mat_props['yield_mpa']} | MPa |
| Elastic Modulus | {mat_props['E_gpa']} | GPa |
| Density | {mat_props['density']} | kg/m³ |

**Why {material.replace('_', ' ').title()}:**
1. **Strength-to-weight ratio:** Highest among common UAV materials
2. **Stiffness:** High elastic modulus minimizes frame flex
3. **Vibration damping:** Better than aluminum
4. **Availability:** Widely available as tubes and sheets

### 5.2 Arm Structural Analysis

#### 5.2.1 Arm Geometry

| Parameter | Value |
|-----------|-------|
| Length | {arm_length:.1f} mm |
| Outer Diameter | {arm_diameter} mm |
| Wall Thickness | {arm_wall} mm |
| Inner Diameter | {arm_diameter - 2*arm_wall:.1f} mm |

#### 5.2.2 Moment of Inertia Calculation

For a hollow circular tube:

$$I = \\frac{{\\pi}}{{4}}(r_o^4 - r_i^4)$$

Where:
- $r_o$ = {r_outer:.1f} mm (outer radius)
- $r_i$ = {r_inner:.1f} mm (inner radius)

$$I = \\frac{{\\pi}}{{4}}({r_outer:.1f}^4 - {r_inner:.1f}^4) = {I:.2f} \\text{{ mm}}^4$$

#### 5.2.3 Bending Stress Analysis

For a cantilever beam (arm) with motor thrust at the end:

$$\\sigma_{{max}} = \\frac{{M \\times c}}{{I}} = \\frac{{F \\times L \\times r_o}}{{I}}$$

Where:
- $F$ = motor thrust force
- $L$ = arm length = {arm_length:.1f} mm
- $c$ = distance to neutral axis = $r_o$ = {r_outer:.1f} mm

**Calculated Maximum Stress:** {max_stress:.2f} MPa

#### 5.2.4 Safety Factor Calculation

$$SF = \\frac{{\\sigma_{{yield}}}}{{\\sigma_{{max}}}} = \\frac{{{mat_props['yield_mpa']}}}{{{max_stress:.2f}}} = {safety_factor:.2f}$$

**Safety Factor: {safety_factor:.2f}** {'✅ > 2.0 (SAFE)' if safety_factor > 2 else '⚠️ < 2.0 (REVIEW)'}

### 5.3 Vibration Analysis

#### 5.3.1 Natural Frequency Calculation

For a cantilever beam, the first natural frequency is:

$$f_n = \\frac{{1.875^2}}{{2\\pi L^2}} \\sqrt{{\\frac{{EI}}{{\\rho A}}}}$$

**Calculated Natural Frequency:** {natural_freq:.1f} Hz

#### 5.3.2 Motor RPM Compatibility

Motor operating frequency = RPM / 60

For typical hover RPM of 8000:
$$f_{{motor}} = \\frac{{8000}}{{60}} = 133 \\text{{ Hz}}$$

**Separation from natural frequency:** {abs(natural_freq - 133):.1f} Hz

{'✅ Good separation - vibration resonance unlikely' if abs(natural_freq - 133) > 20 else '⚠️ Close to motor frequency - may cause resonance'}

### 5.4 Frame Geometry

| Parameter | Value | Note |
|-----------|-------|------|
| Wheelbase | {wheelbase} mm | Motor-to-motor diagonal |
| Minimum Required | {calcs.get('min_wheelbase_mm', 300):.0f} mm | Based on prop diameter |
| Margin | {(wheelbase / calcs.get('min_wheelbase_mm', 300) - 1) * 100:.0f}% | Over minimum |
"""
    
    def _generate_power_analysis(self, state: Dict) -> str:
        """Generate power system analysis with math"""
        power = self._to_dict(state.get('power_design', {}))
        propulsion = self._to_dict(state.get('propulsion_design', {}))
        calcs = power.get('calculations', {})
        battery = power.get('battery', {})
        bat_specs = battery.get('specs', {})
        
        cell_count = bat_specs.get('cell_count', 4)
        capacity = bat_specs.get('capacity_mah', 5000)
        c_rating = bat_specs.get('c_rating', 25)
        battery_weight = bat_specs.get('weight_g', 500)
        
        total_voltage = power.get('total_voltage_v', 22.2)
        total_energy = power.get('total_energy_wh', 100)
        hover_power = power.get('total_hover_power_w', 300)
        flight_time = power.get('calculated_flight_time_min', 20)
        
        # Voltage calculations
        nominal_v = 3.7 * cell_count
        full_v = 4.2 * cell_count
        empty_v = 3.3 * cell_count
        
        return f"""## 6. Power System Analysis

### 6.1 Battery Selection Justification

#### 6.1.1 Energy Requirement Calculation

**Required Flight Time:** {flight_time:.1f} minutes

**Power Consumption at Hover:**

$$P_{{hover}} = {hover_power:.1f} \\text{{ W}}$$

**Energy Required:**

$$E_{{required}} = P_{{hover}} \\times t = {hover_power:.1f} \\times \\frac{{{flight_time:.1f}}}{{60}} = {hover_power * flight_time / 60:.1f} \\text{{ Wh}}$$

**Adding 20% reserve:**

$$E_{{total}} = E_{{required}} \\times 1.2 = {hover_power * flight_time / 60 * 1.2:.1f} \\text{{ Wh}}$$

#### 6.1.2 Battery Capacity Calculation

$$C_{{required}} = \\frac{{E_{{total}}}}{{V_{{nominal}}}} \\times 1000 = \\frac{{{hover_power * flight_time / 60 * 1.2:.1f}}}{{{nominal_v:.1f}}} \\times 1000 = {hover_power * flight_time / 60 * 1.2 / nominal_v * 1000:.0f} \\text{{ mAh}}$$

#### 6.1.3 Selected Battery Specifications

| Parameter | Value | Justification |
|-----------|-------|---------------|
| Cell Configuration | {cell_count}S ({cell_count} cells) | Matches motor KV |
| Capacity | {capacity} mAh | > {hover_power * flight_time / 60 * 1.2 / nominal_v * 1000:.0f} mAh required |
| C Rating | {c_rating}C | Supports max current draw |
| Weight | {battery_weight:.0f} g | Acceptable for AUW target |
| Total Energy | {total_energy:.1f} Wh | Exceeds requirement |

### 6.2 Voltage Analysis

**LiPo Cell Voltage Characteristics:**

| State | Voltage per Cell | Pack Voltage ({cell_count}S) |
|-------|------------------|------------------------------|
| Full Charge | 4.2V | {full_v:.1f}V |
| Nominal | 3.7V | {nominal_v:.1f}V |
| Empty (3.3V) | 3.3V | {empty_v:.1f}V |
| Storage | 3.8V | {3.8 * cell_count:.1f}V |

### 6.3 Current Analysis

#### 6.3.1 Maximum Discharge Current

$$I_{{max}} = C_{{rating}} \\times \\text{{Capacity}} = {c_rating} \\times {capacity/1000:.1f} = {c_rating * capacity / 1000:.0f} \\text{{ A}}$$

#### 6.3.2 Current Consumption

| Flight Mode | Current | Power | Duration |
|-------------|---------|-------|----------|
| Hover | {calcs.get('power_budget', {}).get('propulsion_hover_w', 300) / nominal_v:.1f} A | {calcs.get('power_budget', {}).get('propulsion_hover_w', 300)} W | {capacity / (calcs.get('power_budget', {}).get('propulsion_hover_w', 300) / nominal_v) / 1000 * 60:.0f} min |
| Cruise | {hover_power / nominal_v:.1f} A | {hover_power:.0f} W | {capacity / (hover_power / nominal_v) / 1000 * 60:.0f} min |
| Max Power | {calcs.get('power_budget', {}).get('propulsion_max_w', 1000) / nominal_v:.1f} A | {calcs.get('power_budget', {}).get('propulsion_max_w', 1000)} W | {capacity / (calcs.get('power_budget', {}).get('propulsion_max_w', 1000) / nominal_v) / 1000 * 60:.0f} min |

### 6.4 Flight Time Calculation

**Usable Capacity (80% depth of discharge):**

$$C_{{usable}} = C_{{total}} \\times 0.8 = {capacity} \\times 0.8 = {capacity * 0.8:.0f} \\text{{ mAh}}$$

**Flight Time at Hover:**

$$t_{{flight}} = \\frac{{C_{{usable}}}}{{I_{{hover}}}} \\times 60 = \\frac{{{capacity * 0.8:.0f}}}{{{hover_power / nominal_v:.1f} \\times 1000}} \\times 60 = {capacity * 0.8 / (hover_power / nominal_v) / 1000 * 60:.1f} \\text{{ min}}$$

### 6.5 Power Budget Summary

| Component | Power (W) | Percentage |
|-----------|-----------|------------|
| Propulsion (hover) | {calcs.get('power_budget', {}).get('propulsion_hover_w', 300)} | {calcs.get('power_budget', {}).get('propulsion_hover_w', 300) / hover_power * 100:.1f}% |
| Flight Controller | {calcs.get('power_budget', {}).get('flight_controller_w', 3)} | {calcs.get('power_budget', {}).get('flight_controller_w', 3) / hover_power * 100:.1f}% |
| GPS | {calcs.get('power_budget', {}).get('gps_w', 0.5)} | {calcs.get('power_budget', {}).get('gps_w', 0.5) / hover_power * 100:.2f}% |
| Receiver | {calcs.get('power_budget', {}).get('receiver_w', 0.3)} | {calcs.get('power_budget', {}).get('receiver_w', 0.3) / hover_power * 100:.2f}% |
| Telemetry | {calcs.get('power_budget', {}).get('telemetry_w', 2)} | {calcs.get('power_budget', {}).get('telemetry_w', 2) / hover_power * 100:.2f}% |
| Payload | {calcs.get('power_budget', {}).get('payload_w', 10)} | {calcs.get('power_budget', {}).get('payload_w', 10) / hover_power * 100:.2f}% |
| **Total** | **{hover_power:.1f}** | **100%** |
"""
    
    def _generate_electronics_justification(self, state: Dict) -> str:
        """Generate electronics justification"""
        electronics = self._to_dict(state.get('electronics_design', {}))
        propulsion = self._to_dict(state.get('propulsion_design', {}))
        mission_req = self._to_dict(state.get('mission_requirements', {}))
        calcs = electronics.get('calculations', {})
        
        fc = electronics.get('flight_controller', {})
        # BUG-056: Read correct GPS module key
        gps = electronics.get('gps_module', {}) or electronics.get('gps', {})
        receiver = electronics.get('receiver', {})
        escs = propulsion.get('escs', [{}])
        esc = escs[0] if escs else {}
        
        motor_count = propulsion.get('motor_count', 4)
        
        # Safe extraction for flight controller firmware (BUG-042)
        fc_firmware = fc.get('firmware', fc.get('firmware_support', ['ArduPilot']))
        if isinstance(fc_firmware, str):
            fc_firmware = [fc_firmware]
            
        fc_brand = fc.get('brand', fc.get('manufacturer', 'Generic'))
        gps_brand = gps.get('brand', gps.get('manufacturer', 'Generic'))
        
        return f"""## 7. Electronics Design Justification

### 7.1 Flight Controller Selection

**Selected:** {fc_brand} {fc.get('model', 'N/A')}

#### 7.1.1 Selection Criteria

| Requirement | Needed | Selected FC | Status |
|-------------|--------|-------------|--------|
| Motor Outputs | {motor_count} | {fc.get('specs', {}).get('pwm_outputs', fc.get('specs', {}).get('motor_outputs', 8))} | ✅ |
| Processor | High performance | {fc.get('specs', {}).get('processor', 'STM32')} | ✅ |
| IMU | Precision required | {fc.get('specs', {}).get('imu', 'Dual IMU')} | ✅ |
| UART Ports | ≥4 for peripherals | {fc.get('specs', {}).get('uart_ports', fc.get('specs', {}).get('uarts', 6))} | ✅ |
| Firmware Support | ArduPilot/PX4 | {', '.join(fc_firmware)} | ✅ |

#### 7.1.2 Why This Flight Controller Over Alternatives

1. **vs. Basic F4 FC:** Insufficient processing power for {motor_count}-motor control + autonomy
2. **vs. F7 FC:** Lacks redundant IMU for safety-critical applications
3. **vs. Higher-end options:** This provides best value for requirements

### 7.2 GPS Selection

**Selected:** {gps_brand} {gps.get('model', 'N/A')}

| Feature | Value | Purpose |
|---------|-------|---------|
| Accuracy | {gps.get('specs', {}).get('accuracy_m', 0.8)}m CEP | Precise positioning |
| Update Rate | {gps.get('specs', {}).get('update_rate_hz', 10)} Hz | Smooth navigation |
| Constellations | GPS + GLONASS + Galileo | Global coverage |
| RTK Support | {'Yes' if gps.get('specs', {}).get('rtk', False) else 'No'} | High precision |

### 7.3 ESC Selection

**Selected:** {esc.get('manufacturer', 'N/A')} {esc.get('model', 'N/A')}

#### 7.3.1 Current Rating Verification

**Motor Max Current:** {propulsion.get('motors', [{}])[0].get('max_current_a', 30)}A

**ESC Continuous Rating:** {esc.get('continuous_current_a', 30)}A

$$\\text{{ESC Headroom}} = \\frac{{\\text{{ESC Rating}}}}{{\\text{{Motor Max}}}} = \\frac{{{esc.get('continuous_current_a', 30)}}}{{{propulsion.get('motors', [{}])[0].get('max_current_a', 30)}}} = {esc.get('continuous_current_a', 30) / max(propulsion.get('motors', [{}])[0].get('max_current_a', 30), 1):.2f}$$

{'✅ ESC has adequate headroom' if esc.get('continuous_current_a', 30) >= propulsion.get('motors', [{}])[0].get('max_current_a', 30) else '⚠️ ESC rating should exceed motor max current'}

### 7.4 Receiver Selection

**Selected:** {receiver.get('brand', 'N/A')} {receiver.get('model', 'N/A')}

| Feature | Value | Justification |
|---------|-------|---------------|
| Protocol | {receiver.get('specs', {}).get('protocol', 'ELRS')} | {'Long range capability' if 'Crossfire' in str(receiver.get('specs', {}).get('protocol', '')) else 'Standard control'} |
| Range | {receiver.get('specs', {}).get('range_km', 10)} km | {'Beyond VLOS capable' if mission_req.get('beyond_vlos', False) else 'Adequate for VLOS'} |
| Latency | Low | Critical for responsive control |

### 7.5 Weight and Cost Summary

| Component | Weight (g) | Cost (USD) |
|-----------|------------|------------|
| Flight Controller | {fc.get('specs', {}).get('weight_g', 50)} | {fc.get('price_usd', 0)} |
| GPS | {gps.get('specs', {}).get('weight_g', 30)} | {gps.get('price_usd', 0)} |
| Receiver | {receiver.get('specs', {}).get('weight_g', 10)} | {receiver.get('price_usd', 0)} |
| ESCs (x{motor_count}) | {esc.get('weight_g', 10) * motor_count} | {esc.get('price_usd', 20) * motor_count} |
| **Total** | **{calcs.get('total_electronics_weight_g', 200):.1f}** | **{calcs.get('total_electronics_cost_usd', 500)}** |
"""
    
    def _generate_cog_analysis(self, state: Dict) -> str:
        """Generate center of gravity analysis with math"""
        cog = self._to_dict(state.get('cog_analysis', {}))
        calcs = cog.get('calculations', {})
        
        cg_x = cog.get('cg_x_mm', 0)
        cg_y = cog.get('cg_y_mm', 0)
        cg_z = cog.get('cg_z_mm', 0)
        total_mass = cog.get('total_mass_kg', 2)
        tolerance = cog.get('cg_tolerance_mm', 10)
        within_tol = cog.get('cg_within_tolerance', True)
        
        ixx = cog.get('ixx_kg_m2', 0.1)
        iyy = cog.get('iyy_kg_m2', 0.1)
        izz = cog.get('izz_kg_m2', 0.1)
        
        # Sample components from calculations
        components = calcs.get('component_masses', [])[:10]  # First 10
        
        return f"""## 8. Center of Gravity Analysis

### 8.1 Component Mass Distribution

The CoG is calculated by summing the mass-weighted positions of all components:

$$\\bar{{x}} = \\frac{{\\sum m_i x_i}}{{\\sum m_i}}, \\quad \\bar{{y}} = \\frac{{\\sum m_i y_i}}{{\\sum m_i}}, \\quad \\bar{{z}} = \\frac{{\\sum m_i z_i}}{{\\sum m_i}}$$

#### 8.1.1 Component Positions (Sample)

| Component | Mass (g) | X (mm) | Y (mm) | Z (mm) |
|-----------|----------|--------|--------|--------|
{chr(10).join([f"| {c.get('name', 'Unknown')} | {c.get('mass_g', 0)} | {c.get('x_mm', 0):.1f} | {c.get('y_mm', 0):.1f} | {c.get('z_mm', 0):.1f} |" for c in components[:8]])}
| ... | ... | ... | ... | ... |

### 8.2 Calculated Center of Gravity

| Axis | Position | Tolerance | Status |
|------|----------|-----------|--------|
| X (Roll) | {cg_x:.2f} mm | ±{tolerance} mm | {'✅' if abs(cg_x) <= tolerance else '⚠️'} |
| Y (Pitch) | {cg_y:.2f} mm | ±{tolerance} mm | {'✅' if abs(cg_y) <= tolerance else '⚠️'} |
| Z (Yaw) | {cg_z:.2f} mm | - | - |

**Total Mass:** {total_mass:.3f} kg

**CG Within Tolerance:** {'✅ YES' if within_tol else '❌ NO - Adjust component placement'}

### 8.3 Moment of Inertia Calculations

The moments of inertia determine the drone's rotational dynamics:

$$I_{{xx}} = \\sum m_i (y_i^2 + z_i^2)$$
$$I_{{yy}} = \\sum m_i (x_i^2 + z_i^2)$$
$$I_{{zz}} = \\sum m_i (x_i^2 + y_i^2)$$

| Axis | Moment of Inertia | Unit |
|------|-------------------|------|
| Roll ($I_{{xx}}$) | {ixx:.6f} | kg·m² |
| Pitch ($I_{{yy}}$) | {iyy:.6f} | kg·m² |
| Yaw ($I_{{zz}}$) | {izz:.6f} | kg·m² |

### 8.4 Stability Analysis

**Roll/Pitch Symmetry:**

$$\\frac{{I_{{xx}}}}{{I_{{yy}}}} = \\frac{{{ixx:.6f}}}{{{iyy:.6f}}} = {ixx/max(iyy, 0.0001):.3f}$$

{'✅ Good symmetry (ratio ≈ 1.0)' if 0.9 <= ixx/max(iyy, 0.0001) <= 1.1 else '⚠️ Asymmetric - may affect flight characteristics'}

**Yaw Inertia:**

Higher $I_{{zz}}$ = slower yaw response but more stable in wind.
"""
    
    def _generate_software_justification(self, state: Dict) -> str:
        """Generate software configuration justification"""
        software = self._to_dict(state.get('software_config', {}))
        mission_req = self._to_dict(state.get('mission_requirements', {}))
        cog = self._to_dict(state.get('cog_analysis', {}))
        
        firmware = software.get('firmware_type', 'ArduPilot')
        pids = software.get('pid_values', {})
        modes = software.get('flight_modes', [])
        failsafe = software.get('failsafe_config', {})
        
        auw = cog.get('total_mass_kg', 2)
        
        return f"""## 9. Software Configuration Justification

### 9.1 Firmware Selection: {firmware}

**Why {firmware}:**

| Feature | {firmware} | Alternatives | Winner |
|---------|------------|--------------|--------|
| Open Source | Yes | Varies | {firmware} |
| Autonomy Features | Full | Limited | {firmware} |
| Community Support | Excellent | Good | {firmware} |
| Hardware Support | Wide | Narrow | {firmware} |
| Mission Planning | Advanced | Basic | {firmware} |

### 9.2 PID Tuning Rationale

PID values are scaled based on the All-Up Weight (AUW) of {auw:.2f} kg.

#### 9.2.1 Scaling Formula

For a drone of mass $m$, the PID gains are scaled from baseline values:

$$K_p = K_{{p,base}} \\times \\sqrt{{\\frac{{m}}{{m_{{base}}}}}}$$

Where:
- $K_{{p,base}}$ = baseline P gain (for 1kg reference drone)
- $m$ = actual drone mass
- $m_{{base}}$ = reference mass (1 kg)

#### 9.2.2 Calculated PID Values

| Axis | P | I | D | Notes |
|------|---|---|---|-------|
| Roll | {pids.get('roll', {}).get('P', pids.get('roll', {}).get('p', 0))} | {pids.get('roll', {}).get('I', pids.get('roll', {}).get('i', 0))} | {pids.get('roll', {}).get('D', pids.get('roll', {}).get('d', 0))} | Scaled for {auw:.1f}kg |
| Pitch | {pids.get('pitch', {}).get('P', pids.get('pitch', {}).get('p', 0))} | {pids.get('pitch', {}).get('I', pids.get('pitch', {}).get('i', 0))} | {pids.get('pitch', {}).get('D', pids.get('pitch', {}).get('d', 0))} | Scaled for {auw:.1f}kg |
| Yaw | {pids.get('yaw', {}).get('P', pids.get('yaw', {}).get('p', 0))} | {pids.get('yaw', {}).get('I', pids.get('yaw', {}).get('i', 0))} | - | Higher for yaw authority |

**Note:** These are starting values. Field tuning is required for optimal performance.

### 9.3 Flight Mode Configuration

| Mode # | Mode Name | Purpose |
|--------|-----------|---------|
{chr(10).join([f"| {i+1} | {mode} | {'Primary control' if i == 0 else 'Secondary'} |" for i, mode in enumerate(modes[:6])])}

### 9.4 Failsafe Configuration

| Event | Action | Rationale |
|-------|--------|-----------|
| Signal Loss | {failsafe.get('signal_loss', 'RTL')} | Ensures safe recovery |
| Low Battery | {failsafe.get('battery_low', 'RTL')} | Prevents crash from power loss |
| Critical Battery | {failsafe.get('battery_critical', 'Land')} | Last resort landing |
| GPS Loss | {failsafe.get('gps_loss', 'AltHold')} | Maintains altitude control |
| Geofence Breach | {failsafe.get('geofence', 'RTL')} | Prevents flyaway |
"""
    
    def _generate_wiring_analysis(self, state: Dict) -> str:
        """Generate wiring diagram analysis"""
        wiring = self._to_dict(state.get('wiring_design', {}))
        calcs = wiring.get('calculations', {})
        
        connections = wiring.get('connection_table', [])
        wires = wiring.get('wire_gauge_recommendations', [])
        connectors = wiring.get('connector_list', [])
        
        return f"""## 10. Wiring Design Analysis

### 10.1 Wire Gauge Selection

Wire gauge is selected based on current carrying capacity using the American Wire Gauge (AWG) standard.

#### 10.1.1 Current Capacity Formula

For a given current $I$, the wire gauge is selected such that:

$$I_{{rated}} > I_{{max}} \\times 1.25$$

(25% safety margin)

#### 10.1.2 Wire Gauge Table

| AWG | Max Current (A) | Application |
|-----|-----------------|-------------|
| 22 | 5 | Signal wires |
| 20 | 10 | Low power |
| 18 | 15 | ESC signal |
| 16 | 25 | Motor power (small) |
| 14 | 40 | Motor power (medium) |
| 12 | 60 | Battery main |
| 10 | 80 | High current |

### 10.2 Connection Summary

| Connection Type | Count | Wire Type |
|-----------------|-------|-----------|
| Power (Battery → PDB) | 1 | High current |
| Motor Power | {len([c for c in connections if 'Motor' in str(c.get('to_component', ''))])} | Medium current |
| Signal | {len([c for c in connections if 'signal' in str(c.get('wire_type', '')).lower()])} | Low current |
| **Total** | **{len(connections)}** | |

### 10.3 Connector Selection

| Connector Type | Max Current | Application |
|----------------|-------------|-------------|
| XT60 | 60A | Battery main |
| XT90 | 90A | High power battery |
| Bullet 3.5mm | 30A | Motor connections |
| JST-XH | 3A | Balance leads |
| Servo | 5A | Servos/signal |

### 10.4 EMI/EMC Considerations

{chr(10).join([f"- {note}" for note in calcs.get('emi_notes', ['Keep power and signal wires separated', 'Use twisted pairs for signals', 'Route away from GPS antenna'])])}

### 10.5 Wiring Diagram

A complete wiring diagram is available in: `output/wiring/wiring_diagram.svg`
"""
    
    def _generate_regulatory_compliance(self, state: Dict) -> str:
        """Generate regulatory compliance analysis"""
        regulatory = self._to_dict(state.get('regulatory_compliance', {}))
        mission_req = self._to_dict(state.get('mission_requirements', {}))
        cog = self._to_dict(state.get('cog_analysis', {}))
        
        auw_kg = cog.get('total_mass_kg', 2)
        jurisdictions = regulatory.get('jurisdictions_checked', mission_req.get('jurisdictions', ['India']))
        compliant = regulatory.get('overall_compliant', False)
        requirements = regulatory.get('requirements', [])
        recommendations = regulatory.get('recommendations', [])
        
        return f"""## 11. Regulatory Compliance Analysis

### 11.1 Jurisdictions Analyzed

{chr(10).join([f"- {j}" for j in jurisdictions])}

### 11.2 Weight Classification

**All-Up Weight:** {auw_kg:.2f} kg

| Jurisdiction | Weight Category | Requirements |
|--------------|-----------------|--------------|
| India (DGCA) | {'Nano (<250g)' if auw_kg < 0.25 else 'Micro (<2kg)' if auw_kg < 2 else 'Small (<25kg)' if auw_kg < 25 else 'Medium (<150kg)'} | {'No registration' if auw_kg < 0.25 else 'NPNT + Registration' if auw_kg < 2 else 'Full compliance'} |
| USA (FAA) | {'<250g exempt' if auw_kg < 0.25 else '<55lbs' if auw_kg < 25 else '>55lbs'} | {'Registration recommended' if auw_kg < 0.25 else 'Part 107 registration'} |
| EU (EASA) | {'C0 (<250g)' if auw_kg < 0.25 else 'C1 (<900g)' if auw_kg < 0.9 else 'C2 (<4kg)' if auw_kg < 4 else 'C3/C4'} | {'Open A1' if auw_kg < 0.25 else 'Open A1/A2' if auw_kg < 0.9 else 'Open A2/A3'} |

### 11.3 Compliance Status

**Overall Compliance:** {'✅ COMPLIANT' if compliant else '⚠️ REVIEW REQUIRED'}

#### 11.3.1 Requirements Checklist

| Requirement | Status |
|-------------|--------|
{chr(10).join([f"| {req.get('requirement', 'Unknown')} | {'✅' if req.get('met', False) else '❌'} |" for req in requirements[:10]]) if requirements else "| No specific requirements | ✅ |"}

### 11.4 Recommendations

{chr(10).join([f"1. {rec}" for rec in recommendations[:5]]) if recommendations else "1. Register with local aviation authority before flight"}

### 11.5 Required Equipment for Compliance

| Equipment | Required | Included |
|-----------|----------|----------|
| Remote ID | {'Yes' if auw_kg >= 0.25 else 'No'} | Check FC firmware |
| Anti-collision lights | Yes (night flight) | ✅ LED system included |
| Geofencing | Recommended | ✅ FC supports |
| Return-to-Home | Recommended | ✅ Configured |
"""
    
    def _generate_cost_analysis(self, state: Dict) -> str:
        """Generate cost analysis"""
        bom = self._to_dict(state.get('bill_of_materials', {}))
        mission_req = self._to_dict(state.get('mission_requirements', {}))
        
        items = bom.get('items', [])
        total_cost = bom.get('total_cost', 0)
        currency = bom.get('currency', 'USD')
        budget = mission_req.get('max_cost', 0)
        
        # Group by category
        categories = {}
        for item in items:
            cat = item.get('category', 'Other')
            if cat not in categories:
                categories[cat] = 0
            categories[cat] += item.get('total_price', 0)
        
        # Handle currency conversion (BUG-050: 1 USD = 95 INR)
        budget_currency = mission_req.get('currency', 'INR')
        budget_usd = budget
        if budget_currency == 'INR':
            budget_usd = budget / 95.0
            
        is_within_budget = (total_cost <= budget_usd) if budget_usd > 0 else True
        
        return f"""## 12. Cost Analysis

### 12.1 Budget Summary

| Item | Value |
|------|-------|
| Total Budget | {budget} {budget_currency} |
| Estimated Cost | {total_cost} {currency} |
| Budget Status | {'✅ Within budget' if is_within_budget else '⚠️ Over budget'} |

### 12.2 Cost Breakdown by Category

| Category | Cost ({currency}) | Percentage |
|----------|-------------------|------------|
{chr(10).join([f"| {cat} | {cost:.0f} | {cost/max(total_cost,1)*100:.1f}% |" for cat, cost in sorted(categories.items(), key=lambda x: -x[1])])}
| **Total** | **{total_cost:.0f}** | **100%** |

### 12.3 Component Cost Details

| Item | Qty | Unit Price | Total | Source |
|------|-----|------------|-------|--------|
{chr(10).join([f"| {item.get('item', 'Unknown')[:30]} | {item.get('quantity', 1)} | {item.get('unit_price', 0)} | {item.get('total_price', 0)} | {item.get('source', 'N/A')[:20]} |" for item in items[:15]])}

### 12.4 Cost Optimization Recommendations

1. **Motors:** Consider bulk purchasing for 10-15% discount
2. **Battery:** Evaluate alternative brands with similar specs
3. **Frame:** 3D printing custom parts can reduce costs
4. **Electronics:** Bundle purchases from single supplier for shipping savings
"""
    
    def _generate_appendix(self, state: Dict) -> str:
        """Generate appendix with additional data"""
        return """## Appendix

### A.1 Nomenclature

| Symbol | Description | Unit |
|--------|-------------|------|
| $T$ | Thrust | N |
| $W$ | Weight | N |
| $AUW$ | All-Up Weight | kg |
| $C_D$ | Drag coefficient | - |
| $\\rho$ | Air density | kg/m³ |
| $I$ | Moment of inertia | mm⁴ |
| $\\sigma$ | Stress | MPa |
| $SF$ | Safety factor | - |
| $K_p$, $K_i$, $K_d$ | PID gains | - |

### A.2 References

1. UAV Design Principles - (Various academic sources)
2. Propeller Aerodynamics for Multirotors
3. LiPo Battery Characteristics and Sizing
4. ArduPilot/PX4 Documentation
5. FAA/DGCA/EASA Drone Regulations

### A.3 Output Files

| File | Location | Description |
|------|----------|-------------|
| CAD Model | `output/cad/drone_frame.scad` | OpenSCAD 3D model |
| Wiring Diagram | `output/wiring/wiring_diagram.svg` | SVG wiring diagram |
| Flight Config | `output/software/ardupilot_config.param` | ArduPilot parameters |
| BOM | `output/bom.json` | Bill of Materials |
| Complete Design | `output/complete_design.json` | Full design data |

### A.4 Disclaimer

This design is generated by an AI system and should be reviewed by qualified engineers before construction. All calculations are based on theoretical models and may require adjustment based on actual component specifications and flight testing.

---

*Generated by DroneForge AI - Multi-Agent Drone Design System*
"""
